services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  grafana:
    image: grafana/grafana-oss:latest
    container_name: local_grafana
    ports:
      - '8090:3000'
    depends_on:
      - postgres
      - loki
    networks:
      - app-network

  loki:
    image: grafana/loki:latest
    container_name: loki_local
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app-network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail_local
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      # Format: ./path/to/nestjs/logs:/var/log/nestjs
      - ./logs:/var/log/nestjs
    command: -config.file=/etc/promtail/config.yml
    networks:
      - app-network
    depends_on:
      - loki

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
